from dataclasses import dataclass
from typing import List, Dict, Any


@dataclass
class Alert:
    """Represents a simple alert generated by the rules engine."""
    message: str
    reason: str
    severity: str = "info"  # could be: "info", "warning", "critical"


def evaluate_rules(weather: Dict[str, Any], context: Dict[str, Any] | None = None) -> List[Alert]:
    """
    Given a weather dictionary (like the one returned by get_current_weather_by_city)
    and an optional user context, evaluate a set of rules and return a list of alerts.

    The context can include flags like:
    - has_pets: bool
    - has_plants: bool
    - sensitive_to_cold: bool
    - sensitive_to_heat: bool

    If context is None, default values are used.
    """
    if context is None:
        context = {}

    # Default context values
    has_pets = context.get("has_pets", False)
    has_plants = context.get("has_plants", False)
    sensitive_to_cold = context.get("sensitive_to_cold", False)
    sensitive_to_heat = context.get("sensitive_to_heat", False)

    alerts: List[Alert] = []

    temperature = weather.get("temperature")
    humidity = weather.get("humidity")
    precipitation = weather.get("precipitation")

    # ---- Basic weather rules (general) ----

    # Cold weather
    if temperature is not None and temperature < 5:
        alerts.append(
            Alert(
                message="It is very cold outside. Consider closing windows and protecting plants.",
                reason=f"Temperature below 5°C (currently {temperature}°C)",
                severity="warning",
            )
        )

    # Very hot weather
    if temperature is not None and temperature > 30:
        alerts.append(
            Alert(
                message="It is very hot outside. Make sure pets and plants have enough water.",
                reason=f"Temperature above 30°C (currently {temperature}°C)",
                severity="warning",
            )
        )

    # Dry air
    if humidity is not None and humidity < 30:
        alerts.append(
            Alert(
                message="The air is quite dry. Consider using a humidifier.",
                reason=f"Humidity below 30% (currently {humidity}%)",
                severity="info",
            )
        )

    # Heavy rain
    if precipitation is not None and precipitation > 2:
        alerts.append(
            Alert(
                message="Heavy rain expected. Check balcony, windows and outdoor items.",
                reason=f"Precipitation above 2 mm (currently {precipitation} mm)",
                severity="warning",
            )
        )

    # ---- Context-specific rules ----

    # Pets and heat
    if has_pets and temperature is not None and temperature > 28:
        alerts.append(
            Alert(
                message="It is quite hot and you have pets. Ensure they have shade and fresh water.",
                reason=f"Pets + temperature above 28°C (currently {temperature}°C)",
                severity="warning",
            )
        )

    # Plants and cold
    if has_plants and temperature is not None and temperature < 3:
        alerts.append(
            Alert(
                message="It is close to freezing and you have plants. Consider bringing sensitive plants indoors.",
                reason=f"Plants + temperature below 3°C (currently {temperature}°C)",
                severity="warning",
            )
        )

    # Extra sensitivity: cold
    if sensitive_to_cold and temperature is not None and temperature < 10:
        alerts.append(
            Alert(
                message="You are sensitive to cold. Dress warmly if you need to go outside.",
                reason=f"Sensitive to cold + temperature below 10°C (currently {temperature}°C)",
                severity="info",
            )
        )

    # Extra sensitivity: heat
    if sensitive_to_heat and temperature is not None and temperature > 25:
        alerts.append(
            Alert(
                message="You are sensitive to heat. Consider closing blinds or using a fan.",
                reason=f"Sensitive to heat + temperature above 25°C (currently {temperature}°C)",
                severity="info",
            )
        )

    return alerts
